pipeline:

  build:
    image: maven:3.5.2
    environment:
      - DEPLOY_IMAGE_TAG=0.5
    commands:
      - mvn clean install -DskipTests -Ddeploy_image_tag=$${DEPLOY_IMAGE_TAG} -Ddocker.host=$${DOCKER_HOST} -Pbuild-docker-image -lbuild.out
      - tail -100 build.out
      - grep -q "BUILD SUCCESS" build.out
    secrets: [ docker_host ]

  ## temporary for debugging
  upload-artifacts:
    image: cgswong/aws:s3cmd
    environment:
      - BUCKET=drone.artifacts
    commands:
      - s3cmd --access_key=$${AWS_ACCESS_KEY} --secret_key=$${AWS_SECRET_KEY} --recursive sync $${CI_WORKSPACE}/example/target s3://$${BUCKET}/$${CI_COMMIT_SHA}/
    secrets: [ aws_access_key, aws_secret_key ]

