metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "883"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${aws.cm.cert}
    external-dns.alpha.kubernetes.io/hostname: ${project.artifactId}.${client.ns}.${cluster.domain}.
spec:
  type: LoadBalancer
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
    #nodePort: 31883
  - name: secure-mqtt
    port: 8883
    protocol: TCP
    targetPort: 8883
    #nodePort: 30883
  - name: lb-mqtt
    port: 883
    protocol: TCP
    targetPort: 1883
