spec:
  template:
    spec:
      volumes:
      - name: conf
        secret:
          secretName: ${project.artifactId}-conf
      containers:
      - volumeMounts:
        - name: conf
          mountPath: /run/secrets
        image: ${aws_ecr_uri}/${project.artifactId}:${hono_top_commit}
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///run/secrets/
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: LOGGING_CONFIG
          value: classpath:logback-spring.xml
        - name: _JAVA_OPTIONS
          value: -Xmx196m
