hono:
  app:
    maxInstances: 1
    healthCheckPort: 8088
    healthCheckBindAddress: 0.0.0.0
  http:
    bindAddress: 0.0.0.0
    insecurePortBindAddress: 0.0.0.0
    insecurePortEnabled: true
    keyPath: /run/secrets/http-adapter-key.pem
    certPath: /run/secrets/http-adapter-cert.pem
  messaging:
    name: 'Hono REST Adapter'
    host: ${hono.messaging.host}
    port: 5671
    username: ${hono.adapter.http.username}
    password: ${hono.adapter.http.password}
    trustStorePath: ${hono.trustStore.path}
  registration:
    name: 'Hono REST Adapter'
    host: ${hono.registration.host}
    port: ${hono.registration.port}
    username: ${hono.adapter.http.username}
    password: ${hono.adapter.http.password}
    # Verification is disabled by default. Setting the <em>trustStorePath</em>
    # property enables verification of the server identity implicitly and the
    # value of this property is ignored.
    #trustStorePath: ${hono.trustStore.path}
    hostnameVerificationRequired: ${hono.registration.hostnameVerificationRequired}
    tlsEnabled: ${hono.registration.tlsEnabled}
  credentials:
    name: 'Hono REST Adapter'
    host: ${hono.registration.host}
    port: ${hono.registration.port}
    username: ${hono.adapter.http.username}
    password: ${hono.adapter.http.password}
    # Verification is disabled by default. Setting the <em>trustStorePath</em>
    # property enables verification of the server identity implicitly and the
    # value of this property is ignored.
    #trustStorePath: ${hono.trustStore.path}
    hostnameVerificationRequired: ${hono.registration.hostnameVerificationRequired}
    tlsEnabled: ${hono.registration.tlsEnabled}
  metric:
    reporter:
      graphite:
        active: true
        host: influxdb.${client.ns}
        port: 2003
# disable spring boot actuator endpoints, enable metrics
endpoints:
  enabled: false
  metrics:
    enabled: true
