apiVersion: v1
kind: Route
metadata:
  labels:
    app: hono
    name: ${project.artifactId}
  name: ${project.artifactId}
spec:
  to:
    kind: Service
    name: ${project.artifactId}-ext
  port:
    targetPort: 5671
  tls:
    termination: passthrough
